<?$APPLICATION->IncludeComponent(
	"simpletemplates:form.order", 
	".default", 
	array(
		"AJAX_URL" => "/smt_ajax/ajax_form.php",
		"CUSTOM_FORM_SUBMIT" => "Перезвоните мне",
		"CUSTOM_TITLE_80" => " ",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Ваше имя",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "N",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"EMAIL_TO" => "appart-hotel@yandex.ru",
		"EVENT_MESSAGE_ID" => array(
			0 => "7",
		),
		"FORM_SUFFIX" => "callbackform",
		"GROUPS" => array(
			0 => "2",
		),
		"IBLOCK_ID" => "7",
		"IBLOCK_TYPE" => "smt_form",
		"LEVEL_LAST" => "Y",
		"LIST_URL" => "",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
		"PROPERTY_CODES" => array(
			0 => "39",
			1 => "41",
			2 => "48",
			3 => "NAME",
		),
		"PROPERTY_CODES_REQUIRED" => array(
			0 => "39",
			1 => "41",
			2 => "NAME",
		),
		"REDIRECT_URL" => "",
		"RESIZE_IMAGES" => "N",
		"SEF_MODE" => "N",
		"STATUS" => "ANY",
		"STATUS_NEW" => "NEW",
		"USER_MESSAGE_ADD" => "Ваша заявка успешно отправлена",
		"USER_MESSAGE_EDIT" => "",
		"USE_CAPTCHA" => "N",
		"CUSTOM_TITLE_41" => " ",
		"COMPONENT_TEMPLATE" => ".default",
		"SHOW_FORM_BORDER" => "N",
		"FIELDS_ORDER" => "NAME,39,41,48",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"DISPLAY_ICON" => "Y",
		"FORMS_DISABLE_AGREEMENT" => "N",
		"CUSTOM_TITLE_39" => "",
		"CUSTOM_TITLE_40" => "",
		"CUSTOM_TITLE_42" => "",
		"CUSTOM_TITLE_43" => "",
		"CUSTOM_TITLE_44" => "",
		"CUSTOM_TITLE_45" => "",
		"CUSTOM_TITLE_46" => "",
		"CUSTOM_TITLE_47" => "",
		"CUSTOM_TITLE_48" => ""
	),
	false
);?>